(() => {
  const add=window.GBPAddMaterialQuestions;if(!add)return;
  add({
    12:[
      ['Administrasi perbankan','Pengelolaan dokumen, transaksi, dan data keuangan secara sistematis untuk mendukung operasional bank'],
      ['Akurasi data','Informasi administrasi harus sesuai dengan kondisi dan bukti transaksi yang sebenarnya'],
      ['Validitas data','Data yang digunakan harus sah dan dapat dibuktikan sumbernya'],
      ['Data terupdate','Informasi administrasi perlu diperbarui agar mencerminkan kondisi terkini'],
      ['Jejak audit','Dokumen dan sistem harus memungkinkan riwayat proses ditelusuri kembali'],
      ['Penyimpanan dokumen','Dokumen operasional disimpan sesuai prosedur agar aman dan mudah ditemukan kembali'],
      ['Klasifikasi dokumen','Dokumen dikelompokkan secara konsisten agar pengelolaan dan pencarian lebih efektif'],
      ['Retensi dokumen','Jangka waktu penyimpanan dokumen mengikuti ketentuan yang berlaku'],
      ['Kerahasiaan dokumen','Akses terhadap dokumen nasabah atau transaksi dibatasi hanya kepada pihak berwenang'],
      ['Rekonsiliasi','Pencatatan dibandingkan dengan sumber data lain untuk memastikan tidak ada selisih'],
      ['Laporan administrasi','Ringkasan data operasional disusun untuk kebutuhan monitoring dan pertanggungjawaban'],
      ['Kualitas aset','Penilaian kondisi aset produktif berdasarkan kemampuan memenuhi kewajiban dan kriteria yang berlaku'],
      ['Outstanding kredit','Sisa pokok kredit yang menjadi salah satu data utama dalam perhitungan cadangan kerugian aset'],
      ['Nilai agunan','Informasi jaminan yang diverifikasi sebagai bagian penilaian kualitas dan mitigasi risiko aset'],
      ['Riwayat pembayaran','Catatan ketepatan pembayaran yang membantu menilai kualitas aset atau debitur'],
      ['Lancar 1%','Persentase cadangan pada contoh materi untuk kualitas aset Lancar'],
      ['DPK 5%','Persentase cadangan pada contoh materi untuk kualitas Dalam Perhatian Khusus'],
      ['Kurang Lancar 15%','Persentase cadangan pada contoh materi untuk kualitas Kurang Lancar'],
      ['Diragukan 50%','Persentase cadangan pada contoh materi untuk kualitas Diragukan'],
      ['Macet 100%','Persentase cadangan pada contoh materi untuk kualitas Macet'],
      ['CKPN','Cadangan yang dibentuk untuk mengantisipasi kerugian atas aset sesuai penilaian kualitasnya'],
      ['Verifikasi dokumen','Pemeriksaan kelengkapan dan kebenaran bukti sebelum data dimasukkan atau laporan disusun'],
      ['Pengendalian dokumen','Prosedur untuk memastikan dokumen tidak hilang, berubah tanpa izin, atau diakses pihak tidak berhak'],
      ['Nomor referensi','Identitas unik yang membantu transaksi atau dokumen ditelusuri dalam proses administrasi'],
      ['Otorisasi administrasi','Persetujuan oleh pihak berwenang sebelum dokumen atau transaksi tertentu dinyatakan final'],
      ['Exception report','Laporan yang menyoroti ketidaksesuaian atau transaksi yang membutuhkan tindak lanjut'],
      ['Tindak lanjut selisih','Perbedaan data harus ditelusuri penyebabnya dan diselesaikan, bukan sekadar dicatat'],
      ['Maker-checker','Pemisahan pihak yang membuat dan memeriksa transaksi atau dokumen untuk mengurangi kesalahan'],
      ['Dokumen sumber','Bukti awal yang menjadi dasar pencatatan suatu transaksi atau aktivitas administrasi'],
      ['Arsip aktif','Dokumen yang masih sering digunakan untuk mendukung proses operasional berjalan'],
      ['Arsip inaktif','Dokumen yang jarang digunakan tetapi masih wajib disimpan sesuai ketentuan'],
      ['Konsistensi laporan','Angka dan informasi pada laporan harus dapat direkonsiliasi dengan sumber data pendukung']
    ],
    13:[
      ['Transaksi valuta asing','Pertukaran atau penggunaan mata uang berbeda untuk transaksi internasional, investasi, atau kebutuhan nasabah'],
      ['Devisa Umum','Valas giral atau nonfisik yang didebet atau dikreditkan melalui rekening'],
      ['Bank Notes','Valas kartal atau fisik berupa uang tunai'],
      ['FX Today','Transaksi valuta asing dengan penyelesaian pada hari transaksi sesuai konvensi produk'],
      ['FX Tomorrow','Transaksi valuta asing dengan penyelesaian pada hari kerja berikutnya sesuai konvensi produk'],
      ['FX Spot','Transaksi valuta asing dengan penyelesaian spot sesuai standar pasar'],
      ['FX Forward','Transaksi untuk pertukaran valuta pada tanggal mendatang dengan kurs yang disepakati sebelumnya'],
      ['FX Swap','Kombinasi dua transaksi valas dengan arah berlawanan dan tanggal penyelesaian berbeda'],
      ['Hedging','Strategi untuk mengurangi risiko perubahan kurs terhadap eksposur valuta asing'],
      ['Kurs counter','Kurs yang tersedia pada counter untuk transaksi sesuai batas dan ketentuan bank'],
      ['Kurs special','Kurs khusus yang dapat diberikan pada transaksi tertentu sesuai nominal dan kewenangan'],
      ['Kurs beli','Kurs yang digunakan ketika bank membeli valuta dari nasabah'],
      ['Kurs jual','Kurs yang digunakan ketika bank menjual valuta kepada nasabah'],
      ['Underlying document','Dokumen yang menjelaskan dasar ekonomi atau kebutuhan transaksi valas tertentu'],
      ['Transfer luar negeri','Salah satu kebutuhan nasabah yang menggunakan mata uang asing untuk pengiriman dana lintas negara'],
      ['Perdagangan internasional','Kegiatan ekspor-impor yang menjadi salah satu alasan penggunaan transaksi valas'],
      ['Investasi valas','Penggunaan mata uang asing untuk tujuan investasi sesuai ketentuan'],
      ['Risiko kurs','Potensi kerugian akibat perubahan nilai tukar mata uang'],
      ['Risiko operasional valas','Risiko akibat kesalahan proses, input, dokumen, atau penyelesaian transaksi valas'],
      ['Risiko settlement','Risiko kegagalan salah satu pihak memenuhi kewajiban pada saat penyelesaian transaksi'],
      ['Informasi kurs terkini','Petugas harus menggunakan kurs terbaru ketika memberikan informasi atau memproses transaksi'],
      ['Negosiasi kurs','Proses memperoleh kurs khusus melalui pejabat yang memiliki kewenangan'],
      ['Formulir transaksi valas','Dokumen instruksi yang harus diisi lengkap dan benar sebelum transaksi diproses'],
      ['Kelengkapan dokumen pendukung','Dokumen transaksi valas diperiksa agar tujuan dan persyaratan transaksi dapat diverifikasi'],
      ['Kesesuaian nilai transaksi','Nominal transaksi harus sesuai batas, ketentuan, dan dokumen pendukung yang berlaku'],
      ['DU giral','Karakter Devisa Umum karena transaksi dilakukan melalui rekening, bukan uang fisik'],
      ['BN kartal','Karakter Bank Notes karena valuta yang diperjualbelikan berbentuk uang tunai'],
      ['DU Tod/Tom/Spot/Forward','Jenis tanggal atau produk yang dalam materi dapat dilakukan untuk transaksi Devisa Umum'],
      ['BN Tod/Tom','Jenis tanggal transaksi yang dalam materi digunakan untuk Bank Notes'],
      ['Batas USD 10.000','Nilai yang pada materi digunakan untuk membedakan penerapan kurs counter dan special pada transaksi tertentu'],
      ['SOP valas','Prosedur bank yang harus diikuti selain ketentuan BI dan OJK dalam pemrosesan valuta asing'],
      ['Konfirmasi transaksi','Informasi kurs, nominal, mata uang, dan settlement dikonfirmasi agar kedua pihak memahami detail transaksi']
    ],
    14:[
      ['Letter of Credit','Janji pembayaran bank dalam transaksi perdagangan internasional yang tunduk pada syarat dokumen'],
      ['SKBDN','Instrumen perdagangan berdokumen untuk transaksi dalam negeri sesuai ketentuan yang berlaku'],
      ['Importir','Pihak pembeli yang meminta bank membuka LC atau SKBDN untuk pembayaran barang'],
      ['Eksportir','Pihak penjual yang menerima manfaat pembayaran melalui mekanisme trade'],
      ['Issuing Bank','Bank yang menerbitkan LC atas permintaan applicant'],
      ['Advising Bank','Bank yang meneruskan atau mengadviskan LC kepada beneficiary setelah melakukan pemeriksaan yang diperlukan'],
      ['Applicant','Pihak yang mengajukan penerbitan LC atau SKBDN kepada bank'],
      ['Beneficiary','Pihak penerima manfaat yang berhak mengajukan dokumen sesuai syarat LC'],
      ['Cover tunai 100%','Sumber cover penerbitan LC atau SKBDN berupa dana tunai penuh setelah mendapat persetujuan kewenangan'],
      ['Non Cash Loan','Fasilitas bank yang dapat menjadi dasar penerbitan LC atau SKBDN bila telah disetujui dan tersedia'],
      ['Uncommitted','Sifat limit yang dalam materi dicontohkan untuk fasilitas trade tertentu'],
      ['Revolving','Sifat limit yang dapat digunakan kembali sesuai ketentuan setelah pemakaian berkurang atau dilunasi'],
      ['SWIFT','Jaringan pesan keuangan antarbank yang digunakan untuk komunikasi transaksi internasional'],
      ['Kode bank SWIFT','Bagian awal SWIFT code yang mengidentifikasi institusi bank'],
      ['Kode negara SWIFT','Bagian SWIFT code yang menunjukkan negara institusi'],
      ['Kode lokasi SWIFT','Bagian SWIFT code yang menunjukkan lokasi atau kota'],
      ['Kode cabang SWIFT','Bagian opsional yang dapat menunjukkan cabang atau unit kerja tertentu'],
      ['MT700','Kategori pesan SWIFT untuk penerbitan Letter of Credit'],
      ['MT707','Kategori pesan SWIFT untuk amendment LC'],
      ['MT760','Kategori pesan SWIFT yang digunakan untuk guarantee'],
      ['MT734','Kategori pesan SWIFT untuk advice of discrepancies'],
      ['MT799','Pesan free format pada SWIFT yang digunakan untuk komunikasi terautentikasi sesuai fungsi'],
      ['MT999','Pesan free format non-authenticated yang disebut dalam materi'],
      ['Amendment LC','Perubahan syarat LC yang diterbitkan setelah adanya permintaan dan persetujuan sesuai prosedur'],
      ['Discrepancy','Ketidaksesuaian dokumen dengan syarat LC atau ketentuan yang berlaku'],
      ['Documentary compliance','Prinsip bahwa pembayaran trade sangat bergantung pada kesesuaian dokumen yang dipresentasikan'],
      ['Bill of Lading','Dokumen pengangkutan yang dapat menjadi bagian dokumen perdagangan laut'],
      ['Commercial Invoice','Dokumen tagihan dari penjual yang memuat rincian barang dan nilai transaksi'],
      ['Packing List','Dokumen yang merinci kemasan atau isi pengiriman barang'],
      ['Negotiation','Proses pengambilalihan atau pembayaran dokumen trade oleh bank sesuai persyaratan instrumen'],
      ['Reimbursement','Proses penggantian dana antarbank dalam penyelesaian transaksi trade sesuai instruksi'],
      ['Trade Finance','Pembiayaan yang mendukung kebutuhan modal dan pembayaran dalam rangkaian perdagangan']
    ],
    15:[
      ['Akuntansi perusahaan','Proses pencatatan dan pelaporan transaksi untuk menggambarkan posisi serta kinerja keuangan perusahaan'],
      ['Chart of Accounts','Struktur daftar akun yang digunakan untuk mengklasifikasikan transaksi secara konsisten'],
      ['Aset','Sumber daya yang dikuasai perusahaan dan diharapkan memberi manfaat ekonomi'],
      ['Liabilitas','Kewajiban perusahaan kepada pihak lain yang harus diselesaikan di masa depan'],
      ['Ekuitas','Hak residual pemilik atas aset setelah dikurangi seluruh liabilitas'],
      ['Pendapatan','Kenaikan manfaat ekonomi dari aktivitas perusahaan yang meningkatkan ekuitas selain kontribusi pemilik'],
      ['Beban','Pengorbanan ekonomi yang terjadi untuk menghasilkan pendapatan atau menjalankan kegiatan perusahaan'],
      ['Laporan Posisi Keuangan','Laporan yang menunjukkan aset, liabilitas, dan ekuitas pada suatu tanggal'],
      ['Laporan Laba Rugi','Laporan yang menunjukkan pendapatan, beban, dan laba atau rugi selama suatu periode'],
      ['Laporan Arus Kas','Laporan yang menunjukkan arus masuk dan keluar kas dari aktivitas operasi, investasi, dan pendanaan'],
      ['Laporan Perubahan Ekuitas','Laporan yang menjelaskan pergerakan saldo ekuitas selama periode tertentu'],
      ['Catatan atas Laporan Keuangan','Bagian yang memberi rincian kebijakan, asumsi, dan informasi tambahan atas angka laporan'],
      ['Konsistensi','Prinsip agar metode akuntansi diterapkan secara tetap sehingga informasi antarperiode dapat dibandingkan'],
      ['Relevansi','Prinsip bahwa informasi harus berguna untuk pengambilan keputusan pengguna laporan'],
      ['Dapat diperbandingkan','Karakter informasi yang memungkinkan analisis antarperiode atau antarperusahaan'],
      ['Dapat dipahami','Informasi disajikan dengan struktur dan penjelasan yang dapat dimengerti pengguna yang berkepentingan'],
      ['Pengakuan pendapatan','Penentuan kapan pendapatan dicatat berdasarkan terpenuhinya kriteria akuntansi'],
      ['Pengakuan beban','Penentuan kapan biaya atau pengorbanan ekonomi dicatat dalam periode yang tepat'],
      ['Current Ratio','Rasio likuiditas yang membandingkan aset lancar dengan liabilitas lancar'],
      ['Debt to Equity Ratio','Rasio yang membandingkan total utang dengan ekuitas perusahaan'],
      ['Net Profit Margin','Rasio profitabilitas yang mengukur laba bersih dibanding penjualan atau pendapatan'],
      ['Return on Assets','Rasio yang mengukur kemampuan aset menghasilkan laba'],
      ['Perputaran aset','Rasio efisiensi yang melihat kemampuan aset menghasilkan penjualan'],
      ['Arus kas operasi','Kas yang dihasilkan atau digunakan oleh aktivitas utama perusahaan'],
      ['Arus kas investasi','Kas terkait perolehan atau pelepasan aset jangka panjang dan investasi'],
      ['Arus kas pendanaan','Kas terkait pinjaman, modal, dividen, atau sumber pembiayaan perusahaan'],
      ['Kemampuan bayar','Kapasitas perusahaan memenuhi kewajiban dari arus kas dan sumber keuangannya'],
      ['Analisis likuiditas','Penilaian kemampuan perusahaan memenuhi kewajiban jangka pendek'],
      ['Analisis solvabilitas','Penilaian struktur utang dan kemampuan perusahaan memenuhi kewajiban jangka panjang'],
      ['Analisis profitabilitas','Penilaian kemampuan perusahaan menghasilkan laba dari penjualan atau aset'],
      ['Analisis efisiensi','Penilaian seberapa efektif aset dan biaya digunakan untuk menghasilkan pendapatan'],
      ['Analisis arus kas','Penilaian sumber dan penggunaan kas untuk memahami kemampuan pembayaran nyata perusahaan']
    ],
    16:[
      ['Saldo normal aset','Akun aset memiliki saldo normal debit'],
      ['Saldo normal beban','Akun beban memiliki saldo normal debit'],
      ['Saldo normal liabilitas','Akun liabilitas memiliki saldo normal kredit'],
      ['Saldo normal ekuitas','Akun ekuitas memiliki saldo normal kredit'],
      ['Saldo normal pendapatan','Akun pendapatan memiliki saldo normal kredit'],
      ['Aset bertambah debit','Peningkatan nilai akun aset dicatat di sisi debit'],
      ['Aset berkurang kredit','Penurunan nilai akun aset dicatat di sisi kredit'],
      ['Liabilitas bertambah kredit','Peningkatan kewajiban dicatat di sisi kredit'],
      ['Liabilitas berkurang debit','Penurunan kewajiban dicatat di sisi debit'],
      ['Ekuitas bertambah kredit','Peningkatan ekuitas dicatat di sisi kredit'],
      ['Ekuitas berkurang debit','Penurunan ekuitas dicatat di sisi debit'],
      ['Pendapatan bertambah kredit','Pendapatan yang diakui menambah saldo pada sisi kredit'],
      ['Beban bertambah debit','Beban yang diakui menambah saldo pada sisi debit'],
      ['Laba menambah ekuitas','Laba tahun berjalan pada akhirnya meningkatkan ekuitas sehingga sifat penambahannya kredit'],
      ['Rugi mengurangi ekuitas','Rugi tahun berjalan menurunkan ekuitas sehingga sifat pengurangannya debit'],
      ['Jurnal','Catatan awal transaksi dalam bentuk pasangan debit dan kredit'],
      ['Buku besar','Kumpulan akun yang menampung posting transaksi dari jurnal'],
      ['Neraca saldo','Daftar saldo akun yang digunakan untuk memeriksa keseimbangan debit dan kredit'],
      ['Debit','Sisi pencatatan yang menambah aset atau beban dan mengurangi liabilitas atau ekuitas'],
      ['Kredit','Sisi pencatatan yang menambah liabilitas, ekuitas, atau pendapatan dan mengurangi aset'],
      ['Persamaan akuntansi','Hubungan dasar bahwa aset dibiayai oleh liabilitas dan ekuitas'],
      ['Kas','Akun aset yang mencatat uang tunai dan setara kas sesuai klasifikasi'],
      ['Kredit yang diberikan','Aset bank yang timbul dari penyaluran pinjaman kepada debitur'],
      ['Simpanan nasabah','Liabilitas bank karena dana tersebut merupakan kewajiban bank kepada penyimpan'],
      ['Modal bank','Bagian ekuitas yang menjadi sumber pendanaan pemilik dan penyangga kerugian'],
      ['Pendapatan bunga','Pendapatan yang timbul dari aset produktif seperti kredit sesuai pengakuan yang berlaku'],
      ['Beban bunga','Biaya yang timbul atas sumber dana berbunga seperti simpanan tertentu'],
      ['Fee based income','Pendapatan berbasis jasa yang dicatat sebagai pendapatan ketika memenuhi kriteria pengakuan'],
      ['Cadangan kerugian','Akun yang digunakan untuk mencerminkan estimasi kerugian atas aset sesuai kebijakan akuntansi'],
      ['Posting','Pemindahan informasi transaksi dari jurnal ke akun buku besar'],
      ['Rekonsiliasi akuntansi','Pencocokan saldo buku dengan sumber atau subsistem untuk memastikan kesesuaian'],
      ['Klasifikasi akun','Penempatan transaksi pada akun yang benar agar laporan keuangan mencerminkan substansi transaksi']
    ]
  },{
    12:'1 Mengelola Administrasi Perbankan.pdf',
    13:'2 Memproses Valuta Asing.pdf',
    14:'3 Memproses Trade Services & Trade Finances.pdf',
    15:'4 Mengelola Akuntansi - Perusahaan.pdf',
    16:'5 Mengelola Akuntansi - Perbankan.pdf'
  });
})();