(() => {
  const add=window.GBPAddMaterialQuestions;if(!add)return;
  add({
    1:[
      ['Agent of Trust','Peran bank bertumpu pada kepercayaan masyarakat kepada bank dan kepercayaan bank kepada pihak yang menerima dana'],
      ['Agent of Development','Bank menyalurkan dana untuk mendorong investasi, produksi, pembangunan, dan aktivitas ekonomi'],
      ['Agent of Services','Bank menyediakan jasa transaksi dan layanan keuangan di luar fungsi penghimpunan dan penyaluran dana'],
      ['Financial intermediary','Bank menghubungkan unit surplus dana dengan unit defisit dana'],
      ['Maturity transformation','Bank menghimpun dana berjangka pendek lalu menyalurkannya menjadi kredit berjangka lebih panjang'],
      ['Denomination transformation','Banyak simpanan bernilai kecil digabung menjadi pembiayaan bernilai lebih besar'],
      ['Risk pooling','Risiko disebar melalui portofolio ke banyak debitur atau sektor'],
      ['Bank Umum','Jenis bank yang dapat memberikan jasa dalam lalu lintas pembayaran'],
      ['BPR','Jenis bank yang tidak memberikan jasa dalam lalu lintas pembayaran'],
      ['Giro','Simpanan yang digunakan untuk transaksi pembayaran dan dapat ditarik sesuai ketentuan'],
      ['Tabungan','Simpanan ritel yang fleksibel untuk kebutuhan transaksi dan penyimpanan dana'],
      ['Deposito','Simpanan dengan jangka waktu tertentu dan pencairan mengikuti tenor yang disepakati'],
      ['Bank konvensional','Bank yang menjalankan kegiatan dengan mekanisme bunga sebagai salah satu dasar imbal hasil'],
      ['Bank syariah','Bank yang menjalankan kegiatan berdasarkan prinsip syariah seperti bagi hasil atau murabahah'],
      ['KBMI 1','Kelompok bank dengan modal inti sampai dengan Rp6 triliun'],
      ['KBMI 2','Kelompok bank dengan modal inti lebih dari Rp6 triliun sampai Rp14 triliun'],
      ['KBMI 3','Kelompok bank dengan modal inti lebih dari Rp14 triliun sampai Rp70 triliun'],
      ['KBMI 4','Kelompok bank dengan modal inti di atas Rp70 triliun'],
      ['De Bank van Leening','Lembaga yang didirikan VOC pada 1746 dan disebut sebagai awal perbankan modern di Indonesia dalam materi'],
      ['De Javasche Bank','Bank sirkulasi yang berdiri pada 1828 dan kemudian menjadi bagian penting sejarah Bank Indonesia'],
      ['BNI 1946','Bank pertama milik negara yang didirikan pemerintah pada awal kemerdekaan'],
      ['ORI 1946','Mata uang Republik Indonesia yang diterbitkan pada masa awal kemerdekaan'],
      ['PAKTO 1988','Paket deregulasi yang membuka izin bank baru dan mendorong peningkatan kompetisi perbankan'],
      ['BPPN','Badan yang dibentuk dalam penyehatan perbankan setelah krisis Asia'],
      ['UU No. 10 Tahun 1998','Regulasi yang memperkuat prinsip kehati-hatian dan manajemen risiko setelah krisis perbankan'],
      ['Arsitektur Perbankan Indonesia','Kerangka penguatan struktur dan tata kelola perbankan yang diperkenalkan pada 2004'],
      ['LPS','Lembaga yang menjamin simpanan nasabah penyimpan dan ikut menjaga stabilitas sistem perbankan'],
      ['Proto-bank','Kuil dan istana pada peradaban kuno yang sudah menjalankan fungsi penitipan dan pemberian pinjaman'],
      ['Bills of Exchange','Instrumen pada Eropa abad pertengahan untuk memindahkan dana antar kota tanpa membawa uang tunai'],
      ['Double-entry bookkeeping','Inovasi pembukuan berpasangan yang berkembang pada era bank keluarga di Eropa'],
      ['Bank of England','Bank yang berdiri pada 1694 dan disebut sebagai contoh awal bank sentral modern'],
      ['Joint-stock bank','Bentuk bank berbadan hukum yang menghimpun modal dari pemegang saham untuk membiayai kebutuhan besar'],
      ['Standar emas','Sistem yang mendukung stabilitas nilai tukar pada era konsolidasi perbankan global 1850–1914'],
      ['Letter of Credit','Instrumen yang berkembang untuk mendukung perdagangan ekspor-impor pada era jaringan bank internasional'],
      ['FDIC','Skema asuransi simpanan di Amerika Serikat yang dibentuk pada 1933 setelah krisis perbankan'],
      ['Bretton Woods','Sistem pascaperang yang mengaitkan kurs tetap dengan USD dan emas hingga 1971'],
      ['ATM','Teknologi layanan perbankan yang mulai diperkenalkan pada 1967 dan berkembang dalam era deregulasi'],
      ['Basel III','Reformasi standar modal dan likuiditas yang menguat setelah krisis keuangan global 2008'],
      ['Open Banking','Model yang membuka akses layanan atau data bank melalui API kepada pihak tepercaya dengan persetujuan nasabah'],
      ['Bank-as-a-Service','Model perbankan berbasis platform yang memungkinkan kemampuan bank digunakan pihak lain melalui layanan terintegrasi']
    ],
    2:[
      ['Giro','Produk dana yang lazim digunakan untuk kebutuhan transaksi bisnis dan pembayaran'],
      ['Cek','Warkat yang digunakan dalam rekening giro untuk perintah pembayaran sesuai ketentuan'],
      ['Bilyet Giro','Instrumen giro untuk pemindahbukuan dana kepada pihak penerima'],
      ['Tabungan','Produk dana yang menekankan fleksibilitas, akses ATM, dan kemudahan transaksi'],
      ['Deposito','Produk dana berjangka dengan tenor tetap dan ketentuan pencairan tertentu'],
      ['Low cost fund','Sumber pendanaan berbiaya relatif murah bagi bank yang antara lain berasal dari dana transaksi'],
      ['Transfer','Jasa bank untuk memindahkan dana dari satu pihak atau rekening ke pihak lain'],
      ['Inkaso','Jasa penagihan warkat atau dokumen ke bank atau wilayah lain sesuai mekanisme yang berlaku'],
      ['Kliring','Mekanisme pertukaran dan perhitungan warkat antarbank untuk penyelesaian kewajiban'],
      ['BI-RTGS','Sistem transfer dana bernilai besar yang diselesaikan secara real time gross settlement'],
      ['Bank Draft','Instrumen pembayaran yang diterbitkan bank untuk pembayaran kepada pihak tertentu'],
      ['Traveller Cheque','Instrumen pembayaran yang dirancang untuk kemudahan transaksi saat bepergian'],
      ['Letter of Credit','Jasa bank yang mendukung pembayaran dalam transaksi perdagangan, terutama ekspor-impor'],
      ['Bank Garansi','Jaminan tertulis bank kepada penerima jaminan atas kewajiban pihak yang dijamin'],
      ['Safe Deposit Box','Jasa penyewaan tempat penyimpanan barang atau dokumen berharga di bank'],
      ['e-Banking','Layanan perbankan melalui kanal elektronik untuk transaksi dan akses informasi rekening'],
      ['Pasar Uang','Pasar instrumen keuangan berjangka pendek yang dapat digunakan untuk pengelolaan likuiditas'],
      ['Pasar Modal','Pasar instrumen keuangan berjangka lebih panjang seperti saham dan obligasi'],
      ['Bancassurance','Kerja sama pemasaran produk asuransi melalui kanal atau jaringan bank'],
      ['Wealth Management','Layanan pengelolaan kekayaan nasabah yang menggabungkan kebutuhan investasi dan keuangan'],
      ['ATM','Kanal elektronik yang memberi akses transaksi finansial tanpa harus dilayani teller'],
      ['Mobile Banking','Layanan transaksi bank melalui aplikasi pada perangkat seluler'],
      ['EDC berlogo GPN','Kanal yang memungkinkan transaksi kartu debit pada merchant dalam jaringan pembayaran domestik'],
      ['Remittance','Layanan pengiriman uang, termasuk kebutuhan transfer lintas wilayah atau lintas negara'],
      ['Fee-based services','Kelompok jasa yang memberikan pendapatan berbasis biaya atau fee bagi bank'],
      ['Rekening koran','Catatan mutasi rekening yang lazim menjadi bagian informasi transaksi rekening giro'],
      ['Deposito berjangka','Deposito yang pencairannya mengikuti jangka waktu yang telah disepakati'],
      ['Penalti pencairan awal','Konsekuensi yang dapat timbul ketika deposito dicairkan sebelum jatuh tempo sesuai ketentuan produk'],
      ['Giro untuk bisnis','Karakter produk giro yang banyak digunakan untuk mendukung aktivitas transaksi perusahaan'],
      ['Tabungan fleksibel','Karakter tabungan yang memberi kemudahan transaksi dan akses dana dibanding simpanan berjangka'],
      ['Setoran margin 100%','Salah satu bentuk cover tunai yang dapat digunakan untuk penerbitan Bank Garansi'],
      ['Giro Jaminan Bank Garansi','Rekening giro yang digunakan untuk menempatkan margin tunai sebagai cover Bank Garansi'],
      ['Blokir dana','Mekanisme cover Bank Garansi dengan memblokir dana pada giro, tabungan, atau deposito'],
      ['Non Cash Loan','Fasilitas bank yang dapat menjadi salah satu bentuk cover penerbitan Bank Garansi'],
      ['Counter Guarantee','Jaminan dari pihak lain yang dapat menjadi salah satu sumber cover Bank Garansi'],
      ['Kombinasi cover','Bank Garansi dapat menggunakan gabungan margin tunai, fasilitas Non Cash Loan, dan Counter Guarantee'],
      ['Kartu debit','Kartu transaksi yang membebankan dana secara langsung ke rekening sumber sesuai saldo tersedia'],
      ['Kartu prepaid','Kartu yang menggunakan nilai tersimpan sebelum transaksi dilakukan'],
      ['Internet Banking','Kanal elektronik yang memungkinkan nasabah mengakses layanan bank melalui jaringan internet'],
      ['Analisis perilaku transaksi','Data transaksi nasabah dapat membantu bank memahami pola nasabah sebagai informasi pendukung keputusan layanan atau kredit']
    ],
    3:[
      ['Corporate','Segmen kredit untuk kelompok usaha berskala besar dengan karakteristik dan kebutuhan pembiayaan kompleks'],
      ['Commercial','Segmen kredit bagi usaha komersial dengan skala di bawah corporate sesuai kriteria bank'],
      ['Business Banking','Segmen yang menjembatani kebutuhan pembiayaan usaha antara commercial dan micro sesuai segmentasi bank'],
      ['Micro','Segmen pembiayaan bagi usaha mikro dengan kebutuhan dan pola transaksi yang relatif sederhana'],
      ['Consumer','Segmen kredit untuk kebutuhan konsumsi individu seperti rumah, kendaraan, atau kebutuhan personal'],
      ['Kredit Modal Kerja','Kredit untuk menambah modal kerja seperti bahan baku, produksi, atau pemasaran'],
      ['KMK Revolving','Modal kerja yang dapat ditarik dan disetor kembali berulang selama fasilitas masih berlaku'],
      ['KMK Aflopend','Modal kerja yang pelunasannya mengikuti jadwal angsuran dan tidak dapat ditarik kembali setelah dibayar'],
      ['Kredit Investasi','Kredit untuk membiayai barang modal, modernisasi, perluasan, atau proyek baru'],
      ['Grace period','Masa tenggang pada kredit investasi sampai proyek mulai masuk tahap produksi komersial'],
      ['Commitment fee','Biaya yang pada materi kredit investasi disebut dipungut satu kali saat akad ditandatangani'],
      ['Project Finance','Pembiayaan proyek baru yang dapat mencakup kebutuhan investasi dan modal kerja proyek'],
      ['Kredit Bilateral','Kredit yang pembiayaannya diberikan oleh satu bank'],
      ['Kredit Sindikasi','Kredit yang diberikan dua atau lebih lembaga keuangan dengan dokumen dan ketentuan bersama'],
      ['Agen sindikasi','Pihak yang mengadministrasikan fasilitas kredit sindikasi untuk para pemberi kredit'],
      ['Character','Unsur analisis kredit yang menilai karakter, integritas, dan kemauan membayar calon debitur'],
      ['Capacity','Unsur analisis kredit yang menilai kemampuan debitur menghasilkan arus kas untuk membayar kewajiban'],
      ['Capital','Unsur analisis kredit yang menilai kekuatan permodalan debitur'],
      ['Collateral','Unsur analisis kredit yang menilai agunan sebagai mitigasi risiko tambahan'],
      ['Condition','Unsur analisis kredit yang melihat kondisi usaha, industri, dan ekonomi yang memengaruhi debitur'],
      ['First way out','Sumber pembayaran utama kredit yang berasal dari kemampuan usaha atau arus kas debitur'],
      ['Second way out','Sumber pembayaran sekunder yang antara lain dapat berasal dari eksekusi agunan bila sumber utama gagal'],
      ['Agunan','Aset yang diberikan sebagai jaminan untuk membantu memitigasi risiko kredit'],
      ['Prime rate','Suku bunga kredit debitur yang ditetapkan berdasarkan struktur dan risiko fasilitas'],
      ['Maksimum kredit','Batas nilai fasilitas yang menjadi salah satu faktor dalam penetapan suku bunga kredit'],
      ['Jangka waktu kredit','Tenor fasilitas yang menjadi salah satu faktor dalam penetapan suku bunga kredit'],
      ['Risiko kredit','Risiko kegagalan debitur memenuhi kewajiban pembayaran kepada bank'],
      ['Jenis usaha debitur','Karakter bisnis debitur yang ikut dipertimbangkan dalam struktur fasilitas dan pricing kredit'],
      ['Jaminan kredit','Kualitas dan bentuk jaminan yang ikut memengaruhi penilaian risiko serta suku bunga'],
      ['Kredit konsumtif','Kredit yang digunakan untuk memenuhi kebutuhan konsumsi individu'],
      ['KPR','Kredit konsumtif yang digunakan untuk pembiayaan rumah atau properti tempat tinggal'],
      ['KKB','Kredit konsumtif yang digunakan untuk pembiayaan kendaraan bermotor'],
      ['KTA','Kredit konsumtif tanpa agunan khusus sesuai kebijakan produk'],
      ['Kredit produktif','Kredit yang digunakan untuk mendukung aktivitas usaha seperti modal kerja atau investasi'],
      ['Analisis kelayakan','Penilaian untuk memastikan kebutuhan pembiayaan dan kemampuan bayar debitur dapat dipertanggungjawabkan'],
      ['Segmentasi kredit','Pengelompokan nasabah agar kebijakan, layanan, struktur, dan kewenangan kredit lebih tepat sasaran'],
      ['Gross Annual Sales','Penjualan tahunan bruto yang dapat menjadi salah satu dasar segmentasi bisnis kredit'],
      ['Access to Finance','Akses pembiayaan yang menjadi salah satu faktor dalam penetapan segmentasi bisnis'],
      ['Network','Jaringan usaha yang dapat digunakan sebagai salah satu dasar memahami skala dan karakter segmen'],
      ['Transaction and Technology','Aktivitas transaksi dan tingkat teknologi yang dapat menjadi bagian dasar segmentasi nasabah bisnis']
    ],
    4:[
      ['Bank Indonesia','Otoritas yang berperan pada kebijakan moneter, sistem pembayaran, dan stabilitas makroprudensial'],
      ['OJK','Lembaga yang mengatur dan mengawasi sektor jasa keuangan secara terintegrasi'],
      ['LPS','Lembaga penjamin simpanan yang juga memiliki peran dalam menjaga stabilitas sistem perbankan'],
      ['Prudential banking','Prinsip kehati-hatian yang menuntut bank mengelola risiko sebelum mengambil keputusan bisnis'],
      ['PAKJUN 1983','Paket deregulasi yang antara lain mengubah pengaturan suku bunga perbankan'],
      ['PAKTO 1988','Deregulasi yang membuka pendirian bank baru dan memperbesar kompetisi industri'],
      ['UU No. 10 Tahun 1998','Revisi undang-undang perbankan yang memperkuat kehati-hatian dan manajemen risiko'],
      ['Program Penyehatan Perbankan Nasional','Program pemulihan industri perbankan setelah krisis Asia 1997'],
      ['BPPN','Badan yang menjalankan agenda restrukturisasi dan penyehatan bank setelah krisis'],
      ['Arsitektur Perbankan Indonesia','Kebijakan 2004 yang diarahkan pada penguatan struktur industri dan tata kelola'],
      ['UU No. 24 Tahun 2004','Undang-undang yang menjadi dasar pembentukan Lembaga Penjamin Simpanan'],
      ['Good Corporate Governance','Tata kelola yang menekankan transparansi, akuntabilitas, tanggung jawab, independensi, dan kewajaran'],
      ['BUKU','Klasifikasi bank yang pernah digunakan berdasarkan kegiatan usaha dan modal sebelum pendekatan KBMI'],
      ['KBMI','Klasifikasi bank berdasarkan kelompok modal inti'],
      ['Kebijakan moneter','Kebijakan untuk menjaga kestabilan nilai rupiah melalui instrumen moneter'],
      ['Sistem pembayaran','Infrastruktur dan mekanisme pemindahan dana yang menjadi salah satu area tugas Bank Indonesia'],
      ['Makroprudensial','Pendekatan pengawasan yang melihat risiko sistem keuangan secara keseluruhan'],
      ['Mikroprudensial','Pengawasan yang berfokus pada kesehatan dan kepatuhan masing-masing lembaga jasa keuangan'],
      ['Penjaminan simpanan','Fungsi yang meningkatkan kepercayaan masyarakat terhadap dana yang ditempatkan di bank'],
      ['Resolusi bank','Penanganan bank bermasalah agar dampaknya terhadap sistem dapat dikelola'],
      ['Pembatasan pihak terkait','Salah satu penguatan pascakrisis untuk menekan risiko kredit kepada kelompok terafiliasi'],
      ['Manajemen risiko','Kerangka identifikasi, pengukuran, pemantauan, dan pengendalian risiko dalam kegiatan bank'],
      ['Konsolidasi bank','Proses penguatan struktur industri melalui penggabungan atau penataan bank agar lebih sehat'],
      ['Kepercayaan publik','Tujuan penting regulasi karena industri bank bergantung pada kepercayaan penyimpan dana'],
      ['Stabilitas sistem keuangan','Kondisi ketika fungsi intermediasi dan pembayaran dapat berjalan tanpa gangguan sistemik besar'],
      ['Regulasi perbankan','Ketentuan yang membatasi dan mengarahkan kegiatan bank agar aman serta sesuai hukum'],
      ['Pengawasan bank','Aktivitas memastikan bank menjalankan ketentuan, menjaga kesehatan, dan mengelola risiko'],
      ['Deregulasi','Pelonggaran aturan tertentu untuk mendorong kompetisi dan perkembangan industri'],
      ['Krisis Asia 1997','Peristiwa yang memicu restrukturisasi besar dan perubahan regulasi perbankan Indonesia'],
      ['Moral hazard','Perilaku mengambil risiko karena dampak negatifnya tidak sepenuhnya ditanggung oleh pengambil keputusan'],
      ['Kredit kepada grup sendiri','Praktik pascakrisis yang menjadi perhatian karena meningkatkan risiko konsentrasi dan benturan kepentingan'],
      ['Pengawasan terintegrasi','Pengawasan lintas sektor jasa keuangan agar risiko konglomerasi dapat dilihat secara menyeluruh'],
      ['Ketahanan modal','Kemampuan modal menyerap kerugian dan mendukung kelangsungan usaha bank'],
      ['Likuiditas','Kemampuan bank memenuhi kewajiban pembayaran ketika jatuh tempo'],
      ['Transparansi','Prinsip tata kelola yang menuntut informasi material disampaikan secara memadai'],
      ['Akuntabilitas','Prinsip tata kelola yang menegaskan kejelasan fungsi dan pertanggungjawaban organ bank'],
      ['Independensi','Prinsip tata kelola yang mencegah dominasi dan benturan kepentingan dalam pengambilan keputusan'],
      ['Responsibility','Prinsip tata kelola yang menuntut kepatuhan terhadap regulasi dan tanggung jawab korporasi'],
      ['Fairness','Prinsip tata kelola yang menuntut perlakuan wajar terhadap pemangku kepentingan'],
      ['Regulatory reset','Gambaran perubahan besar setelah krisis ketika industri direstrukturisasi agar lebih sehat dan prudent']
    ],
    5:[
      ['Financial Intermediary','Dalam ekosistem, bank menyediakan akses kredit, investasi, dan pembayaran'],
      ['Trusted Data Custodian','Bank dipercaya menyimpan data dan riwayat transaksi nasabah'],
      ['Platform Provider','Bank menyediakan API atau kapabilitas banking untuk dipakai partner ekosistem'],
      ['Investor & Partner','Bank dapat masuk ke ekosistem melalui investasi atau kemitraan strategis'],
      ['Enabler','Bank membantu pelaku ekosistem menjalankan aktivitas bisnis melalui akses layanan keuangan'],
      ['Orchestrator','Bank menghubungkan dan mengoordinasikan berbagai pelaku agar nilai ekosistem tercipta'],
      ['Open Banking','Pembukaan data atau layanan bank melalui API kepada pihak tepercaya dengan persetujuan nasabah'],
      ['API Banking','Antarmuka yang memungkinkan sistem partner mengakses fungsi perbankan secara terkontrol'],
      ['Embedded Finance','Layanan keuangan yang ditanamkan langsung ke dalam perjalanan pelanggan pada platform nonbank'],
      ['Corporate Venture Capital','Salah satu cara bank berinvestasi pada perusahaan atau startup yang relevan dengan ekosistem'],
      ['Fintech','Perusahaan teknologi keuangan yang dapat menjadi partner maupun kompetitor bank dalam ekosistem'],
      ['Bigtech','Perusahaan teknologi berskala besar yang dapat masuk ke layanan keuangan melalui basis pengguna dan data'],
      ['Pemerintah','Pelaku ekosistem yang berperan dalam kebijakan, layanan publik, dan kemitraan ekonomi'],
      ['UMKM','Pelaku usaha yang dapat menjadi bagian rantai pasok, merchant, debitur, atau nasabah transaksi dalam ekosistem'],
      ['Startup','Pelaku inovasi yang dapat menyediakan solusi teknologi atau model bisnis baru bagi ekosistem'],
      ['Konsumen','Pihak akhir yang menggunakan produk, layanan, dan pengalaman yang dibentuk oleh ekosistem'],
      ['Technology Provider','Penyedia infrastruktur atau solusi teknologi yang mendukung integrasi para pelaku'],
      ['Fee-based income','Pendapatan berbasis transaksi atau jasa yang dapat meningkat ketika aktivitas ekosistem bertambah'],
      ['Risiko keamanan data','Tantangan ekosistem ketika data bergerak dan diproses lintas sistem atau partner'],
      ['Ketergantungan partner','Risiko operasional ketika kualitas layanan bank ikut bergantung pada pihak eksternal'],
      ['Tekanan margin','Tantangan ketika persaingan dan pembagian nilai antar pelaku menekan keuntungan masing-masing pihak'],
      ['Customer-centric','Pendekatan yang merancang ekosistem berdasarkan kebutuhan dan perjalanan pelanggan'],
      ['Value creation','Tujuan kolaborasi ekosistem untuk menghasilkan manfaat yang lebih besar bagi para pelaku dan pelanggan'],
      ['Kolaborasi','Cara kerja utama ekosistem karena nilai tidak diciptakan oleh satu organisasi saja'],
      ['Interkoneksi','Hubungan antar pelaku, proses, data, dan platform yang memungkinkan ekosistem bekerja sebagai jaringan'],
      ['Partner ecosystem','Jaringan mitra yang melengkapi kapabilitas bank untuk memberi solusi end-to-end'],
      ['Data-driven banking','Pemanfaatan data untuk memahami kebutuhan, perilaku, dan peluang dalam ekosistem'],
      ['Digital platform','Infrastruktur yang mempertemukan banyak pelaku dan memungkinkan transaksi berlangsung secara terintegrasi'],
      ['Network effect','Nilai platform dapat meningkat ketika semakin banyak pengguna atau partner berpartisipasi'],
      ['Cross-selling','Pemanfaatan kebutuhan ekosistem untuk menawarkan produk lain yang relevan kepada nasabah'],
      ['Supply chain','Rangkaian pemasok, produsen, distributor, dan pembeli yang dapat dipetakan sebagai ekosistem pembiayaan dan transaksi'],
      ['Payment ecosystem','Jaringan issuer, acquirer, merchant, switch, dan pelanggan yang mendukung transaksi pembayaran'],
      ['Merchant','Pelaku usaha penerima pembayaran yang menjadi titik penting dalam ekosistem transaksi'],
      ['Anchor client','Pelaku utama yang memiliki hubungan bisnis dengan banyak pemasok atau distributor dan dapat menjadi pusat ekosistem'],
      ['Supplier','Pemasok dalam rantai nilai yang dapat membutuhkan pembiayaan modal kerja dan layanan transaksi'],
      ['Distributor','Pelaku yang menyalurkan barang dan dapat menjadi bagian arus transaksi maupun pembiayaan ekosistem'],
      ['Cash management','Layanan yang membantu perusahaan mengelola penerimaan, pembayaran, dan likuiditas dalam ekosistem'],
      ['Transaction banking','Layanan pembayaran dan pengelolaan transaksi yang menjadi fondasi hubungan bank dengan ekosistem bisnis'],
      ['Consent','Persetujuan nasabah yang diperlukan ketika data atau layanan dibuka kepada pihak ketiga dalam open banking'],
      ['Shared value','Manfaat yang dibangun bersama sehingga bank, partner, dan pelanggan sama-sama memperoleh nilai']
    ],
    6:[
      ['ATM','Teknologi awal digitalisasi yang memungkinkan layanan tunai dan transaksi tanpa teller'],
      ['Core Banking System','Sistem inti yang mengintegrasikan pencatatan rekening dan transaksi bank'],
      ['Kartu Kredit dan Debit','Instrumen pembayaran elektronik yang berkembang pada era awal digitalisasi'],
      ['Internet Banking','Layanan bank melalui web yang berkembang luas pada era internet'],
      ['SMS Banking','Layanan transaksi dan informasi melalui pesan singkat pada fase awal mobile banking'],
      ['Mobile Banking','Layanan perbankan melalui aplikasi seluler yang menjadi kanal utama nasabah digital'],
      ['Payment Gateway','Infrastruktur yang menghubungkan merchant dengan kanal pembayaran untuk transaksi digital'],
      ['e-Commerce','Ekosistem perdagangan digital yang mendorong kebutuhan pembayaran online'],
      ['E-Wallet','Dompet digital seperti GoPay, OVO, DANA, atau LinkAja yang menjadi bagian disrupsi pembayaran'],
      ['P2P Lending','Platform yang mempertemukan pemberi dan penerima dana secara digital di luar model bank tradisional'],
      ['Crowdfunding','Pengumpulan dana dari banyak pihak melalui platform digital untuk tujuan tertentu'],
      ['QR Payment','Pembayaran yang menggunakan kode QR sebagai media instruksi transaksi'],
      ['Contactless Payment','Pembayaran tanpa kontak fisik langsung antara kartu atau perangkat dan terminal'],
      ['Bank Digital Full Online','Model bank yang sebagian besar perjalanan nasabahnya dilakukan secara digital'],
      ['Open Banking API','Integrasi layanan bank dengan partner melalui API'],
      ['Big Data','Pengolahan data berukuran besar untuk analisis perilaku dan pengambilan keputusan'],
      ['Artificial Intelligence','Teknologi yang dapat digunakan untuk skoring, deteksi fraud, dan personalisasi layanan'],
      ['Chatbot','Asisten otomatis untuk melayani pertanyaan atau kebutuhan dasar nasabah'],
      ['Virtual Assistant','Layanan digital berbasis percakapan yang membantu interaksi nasabah dengan bank'],
      ['Embedded Finance','Integrasi produk keuangan langsung ke dalam platform atau proses bisnis pihak lain'],
      ['Digital Identity','Identitas elektronik yang mendukung autentikasi dan layanan perbankan digital'],
      ['e-KYC','Proses mengenali dan memverifikasi nasabah secara elektronik'],
      ['Blockchain','Teknologi distributed ledger yang digunakan dalam eksperimen berbagai layanan keuangan'],
      ['CBDC','Mata uang digital yang diterbitkan oleh bank sentral'],
      ['Wealthtech','Pemanfaatan teknologi untuk investasi dan pengelolaan kekayaan ritel'],
      ['Mobile-first','Perilaku nasabah yang menjadikan perangkat seluler sebagai kanal utama berinteraksi'],
      ['Cashless society','Perubahan perilaku masyarakat menuju penggunaan pembayaran non-tunai'],
      ['Omni-channel','Pengalaman nasabah melalui banyak kanal yang saling terintegrasi'],
      ['Neobank','Model bank atau layanan bank digital dengan fokus kuat pada pengalaman digital'],
      ['BNPL','Buy Now Pay Later sebagai bentuk pembiayaan digital pada perjalanan pembelian'],
      ['Alternative data','Data nontradisional yang dapat digunakan untuk memperkaya analisis kredit digital'],
      ['PSD2','Regulasi di Eropa yang sering dijadikan contoh perkembangan open banking'],
      ['Bank-as-a-Service','Penyediaan kapabilitas bank agar dapat digunakan platform atau perusahaan lain'],
      ['Real-time payment','Pembayaran yang diproses dan diterima secara cepat hampir seketika'],
      ['AI credit scoring','Penggunaan kecerdasan buatan untuk membantu menilai kelayakan kredit'],
      ['Fraud detection','Pemanfaatan teknologi untuk mendeteksi pola transaksi yang mengindikasikan kecurangan'],
      ['Personalization','Pemanfaatan data dan analitik untuk menyesuaikan penawaran dengan kebutuhan nasabah'],
      ['Customer experience','Kualitas pengalaman nasabah yang menjadi fokus utama persaingan bank digital'],
      ['Platform banking','Model ketika bank beroperasi sebagai bagian dari jaringan layanan dan partner digital'],
      ['Cybersecurity','Pengamanan sistem, data, identitas, dan transaksi sebagai fondasi layanan perbankan digital']
    ]
  },{
    1:'Full General Banking!!!.pdf · Peran, Jenis, dan Sejarah Perbankan',
    2:'2 Produk dan Jasa Perbankan - Dana.pdf',
    3:'3 Produk dan Jasa Perbankan - Kredit.pdf',
    4:'4 Regulasi dan Otoritas.pdf',
    5:'5 Business Ecosystem.pdf',
    6:'Full General Banking!!!.pdf · The Future of Banking'
  });
})();