(() => {
  const add=window.GBPAddMaterialQuestions;if(!add)return;
  add({
    7:[
      ['Identifikasi kebutuhan informasi','Petugas terlebih dahulu menggali produk, fitur, biaya, risiko, atau proses apa yang ingin diketahui nasabah'],
      ['Tujuan pelayanan informasi','Pelayanan perlu memiliki sasaran yang jelas agar informasi yang diberikan benar-benar menjawab kebutuhan nasabah'],
      ['Kesiapan media informasi','Brosur, tarif, simulasi, aplikasi, atau sarana lain perlu tersedia dan mutakhir sebelum pelayanan diberikan'],
      ['Kejelasan informasi produk','Fitur dan manfaat produk dijelaskan dengan bahasa yang dapat dipahami nasabah'],
      ['Informasi biaya','Nasabah perlu mengetahui biaya administrasi, penalti, atau biaya transaksi yang melekat pada produk'],
      ['Informasi risiko','Petugas tidak hanya menyampaikan manfaat, tetapi juga risiko atau konsekuensi penggunaan produk'],
      ['Informasi syarat','Persyaratan pembukaan, penggunaan, atau pemanfaatan produk harus disampaikan secara lengkap'],
      ['Informasi ketentuan','Batasan dan aturan produk perlu dijelaskan sesuai ketentuan bank yang berlaku'],
      ['Kesesuaian dengan SOP','Informasi yang diberikan harus mengikuti prosedur dan standar operasional bank'],
      ['Kesesuaian dengan regulasi','Penjelasan produk tidak boleh bertentangan dengan ketentuan regulator'],
      ['Transparansi','Informasi material tidak boleh disembunyikan hanya demi mengejar penjualan'],
      ['Bahasa sederhana','Istilah teknis perlu diterjemahkan menjadi penjelasan yang mudah dipahami nasabah'],
      ['Konfirmasi pemahaman','Petugas memastikan kembali bahwa nasabah memahami informasi yang baru dijelaskan'],
      ['Tindak lanjut pertanyaan','Pertanyaan yang belum dapat dijawab saat itu harus diteruskan atau ditindaklanjuti sampai jelas'],
      ['Umpan balik nasabah','Respons nasabah digunakan untuk menilai apakah cara penyampaian informasi sudah efektif'],
      ['Peningkatan kualitas layanan','Hasil evaluasi pelayanan dipakai untuk memperbaiki pengalaman nasabah pada layanan berikutnya'],
      ['Kesesuaian kebutuhan nasabah','Produk yang dijelaskan harus relevan dengan kebutuhan, bukan semata produk yang sedang ditargetkan'],
      ['Perbandingan produk','Jika relevan, petugas menjelaskan perbedaan fitur produk agar nasabah dapat memilih secara sadar'],
      ['Manfaat produk','Nilai guna produk bagi kebutuhan nasabah perlu dijelaskan secara spesifik'],
      ['Karakteristik produk','Petugas perlu menguasai sifat dasar produk sebelum memberikan informasi kepada nasabah'],
      ['Kanal layanan','Informasi dapat diberikan melalui kantor, kanal digital, call center, atau media resmi bank sesuai kebutuhan'],
      ['Sumber informasi resmi','Petugas menggunakan referensi resmi bank, bukan asumsi atau informasi tidak terverifikasi'],
      ['Pembaruan informasi','Perubahan tarif, fitur, regulasi, atau prosedur harus tercermin pada materi informasi yang digunakan'],
      ['Batas kewenangan','Petugas tidak memberikan komitmen di luar kewenangannya dan melakukan eskalasi bila diperlukan'],
      ['Eskalasi informasi','Pertanyaan kompleks diteruskan kepada unit atau pejabat yang kompeten'],
      ['Akurasi informasi','Nominal, tarif, tenor, fitur, dan ketentuan yang disampaikan harus benar'],
      ['Konsistensi informasi','Nasabah seharusnya memperoleh informasi pokok yang sama dari kanal resmi yang berbeda'],
      ['Dokumentasi pelayanan','Interaksi tertentu perlu tercatat bila prosedur mensyaratkannya agar dapat ditelusuri'],
      ['Pelindungan konsumen','Penyampaian informasi harus membantu nasabah mengambil keputusan yang wajar dan terinformasi'],
      ['Tidak menyesatkan','Petugas tidak boleh melebihkan manfaat atau mengecilkan risiko produk'],
      ['Ketepatan waktu','Informasi diberikan saat masih relevan untuk keputusan atau transaksi nasabah'],
      ['Customer experience','Kualitas pelayanan dinilai bukan hanya dari kecepatan, tetapi juga kejelasan dan ketepatan informasi']
    ],
    8:[
      ['Tujuan edukasi','Program edukasi dimulai dengan hasil belajar atau perubahan pemahaman yang ingin dicapai'],
      ['Segmentasi peserta','Materi dan metode dipilih berdasarkan karakter kelompok sasaran edukasi'],
      ['Analisis kebutuhan belajar','Penyelenggara menilai kesenjangan pengetahuan peserta sebelum menentukan materi'],
      ['Rencana program edukasi','Tujuan, peserta, jadwal, lokasi, metode, sarana, dan evaluasi disusun sebelum pelaksanaan'],
      ['Workshop','Metode edukasi langsung melalui sesi pembelajaran terstruktur dan interaktif'],
      ['Pelatihan','Metode edukasi untuk membangun pengetahuan dan keterampilan keuangan secara lebih sistematis'],
      ['Konsultasi keuangan','Edukasi langsung yang menyesuaikan pembahasan dengan kebutuhan finansial individu'],
      ['Simulasi produk','Peserta belajar melalui contoh penggunaan, biaya, manfaat, atau perhitungan produk keuangan'],
      ['Kemitraan sekolah','Program literasi dapat dilakukan melalui kerja sama dengan sekolah atau universitas'],
      ['Kemitraan pemerintah','Program edukasi dapat diperluas melalui kolaborasi dengan instansi pemerintah'],
      ['Kemitraan lembaga keuangan','Program dapat melibatkan lembaga keuangan lain bila mendukung tujuan edukasi'],
      ['Aplikasi mobile','Kanal digital yang dapat digunakan untuk menyampaikan materi literasi secara berkelanjutan'],
      ['Website','Media digital untuk publikasi materi edukasi yang dapat diakses peserta secara mandiri'],
      ['Media sosial','Kanal edukasi yang efektif untuk konten singkat dan jangkauan peserta yang luas'],
      ['Webinar','Metode edukasi daring yang memungkinkan penyampaian materi dan interaksi jarak jauh'],
      ['Live streaming','Penyampaian edukasi digital secara langsung melalui kanal online'],
      ['Manajemen keuangan pribadi','Topik edukasi tentang mengatur pendapatan, pengeluaran, tabungan, dan tujuan keuangan'],
      ['Pentingnya menabung','Topik literasi yang membangun kebiasaan menyisihkan dana untuk kebutuhan dan tujuan masa depan'],
      ['Pengelolaan utang sehat','Topik edukasi tentang kemampuan bayar, biaya utang, dan risiko keterlambatan'],
      ['Pemahaman tabungan','Materi tentang fungsi, manfaat, akses, dan karakter produk tabungan'],
      ['Pemahaman deposito','Materi tentang tenor, imbal hasil, dan konsekuensi pencairan sebelum jatuh tempo'],
      ['Pemahaman giro','Materi tentang penggunaan rekening transaksi terutama untuk kebutuhan pembayaran'],
      ['Pemahaman kredit','Materi tentang kewajiban membayar, tenor, bunga atau biaya, dan risiko kredit'],
      ['Keamanan akun','Materi tentang cara menjaga kredensial dan akses terhadap layanan digital'],
      ['Modus penipuan','Materi untuk membantu nasabah mengenali social engineering dan pola penipuan finansial'],
      ['OTP','Kode autentikasi yang tidak boleh dibagikan kepada pihak lain'],
      ['PIN','Informasi rahasia yang harus dijaga oleh pengguna untuk keamanan transaksi'],
      ['Verifikasi dua langkah','Lapisan autentikasi tambahan untuk memperkuat keamanan akses akun'],
      ['QRIS dan dompet digital','Contoh materi inklusi dan digitalisasi pembayaran yang dapat dikenalkan kepada peserta'],
      ['Identifikasi pemahaman nasabah','Di kantor cabang, petugas menilai dulu tingkat pengetahuan nasabah sebelum memberi penjelasan'],
      ['Panduan sesuai kebutuhan','Petugas menyesuaikan isi edukasi dengan tujuan finansial dan tingkat literasi nasabah'],
      ['Evaluasi program','Hasil kegiatan diukur lalu digunakan sebagai dasar perbaikan program edukasi berikutnya']
    ],
    9:[
      ['Pengaduan lisan','Keluhan dapat disampaikan langsung atau melalui telepon dan tetap wajib diterima serta dicatat bank'],
      ['Pengaduan tertulis','Keluhan melalui surat atau email diproses sebagai pengaduan tertulis sesuai prosedur'],
      ['Registrasi pengaduan','Setiap pengaduan dicatat agar memiliki identitas dan dapat ditelusuri proses penyelesaiannya'],
      ['Nomor registrasi','Nasabah memperoleh nomor yang digunakan untuk mengidentifikasi pengaduannya'],
      ['Tanggal pengaduan','Tanggal penerimaan dicatat karena menjadi acuan pengelolaan jangka waktu penyelesaian'],
      ['Tanda terima','Bank memberikan bukti bahwa pengaduan telah diterima'],
      ['Verifikasi nasabah','Bank memastikan identitas pihak yang mengajukan pengaduan sebelum memproses informasi dan transaksi'],
      ['Surat kuasa','Dokumen diperlukan apabila pengaduan diajukan oleh perwakilan nasabah'],
      ['Informasi transaksi','Jenis transaksi, tanggal kejadian, dan permasalahan diperlukan untuk menganalisis pengaduan'],
      ['Kelengkapan dokumen','Dokumen pendukung harus dipenuhi agar pengaduan dapat dianalisis secara memadai'],
      ['20 hari kerja pelengkapan dokumen','Materi memberi waktu bagi nasabah untuk melengkapi kekurangan dokumen pengaduan'],
      ['Pemeriksaan internal','Bank menindaklanjuti pengaduan dengan pemeriksaan yang kompeten dan benar'],
      ['Analisis objektif','Kebenaran pengaduan ditentukan berdasarkan fakta dan prosedur, bukan asumsi petugas'],
      ['Tanggapan pengaduan','Bank wajib menyampaikan hasil penanganan kepada nasabah'],
      ['Tanggapan tertulis','Pengaduan tertulis memperoleh tanggapan secara tertulis'],
      ['Tanggapan lisan atau tertulis','Pengaduan lisan dapat ditanggapi secara lisan dan/atau tertulis'],
      ['Penjelasan permasalahan','Jika tidak ada kesalahan bank, tanggapan dapat berupa penjelasan atas hasil pemeriksaan'],
      ['Penawaran penyelesaian','Jika kesalahan bank menyebabkan kerugian nasabah, bank dapat menawarkan penyelesaian'],
      ['5 hari kerja','Materi menyebut batas penyelesaian pengaduan lisan dalam kondisi yang dipersyaratkan'],
      ['20 hari kerja','Materi menyebut batas penyelesaian pengaduan tertulis sejak pengaduan diterima'],
      ['Perpanjangan tertulis','Jika penyelesaian diperpanjang, pemberitahuan kepada nasabah wajib dilakukan secara tertulis'],
      ['Tindak lanjut pihak lain','Penyelesaian dapat melewati jangka waktu ketika proses bergantung pada pihak lain'],
      ['Penelitian khusus','Kebutuhan penelitian khusus dapat menjadi alasan perpanjangan penanganan sesuai ketentuan'],
      ['Status pengaduan','Bank wajib menyediakan informasi perkembangan penanganan ketika diminta nasabah'],
      ['Unit penerima pengaduan','Cabang, call center, kanal resmi, dan unit kerja dapat menjadi pintu masuk pengaduan'],
      ['Unit penyelesaian pengaduan','Unit yang memiliki domain masalah bertanggung jawab melakukan penyelesaian substantif'],
      ['Unit pengelola pengaduan','Unit pengelola mengoordinasikan administrasi dan pengelolaan pengaduan'],
      ['Indikasi fraud','Pengaduan dengan indikasi kecurangan ditangani sesuai strategi anti fraud dan melibatkan fungsi terkait'],
      ['Penolakan karena dokumen tidak lengkap','Bank dapat menolak penanganan jika persyaratan dokumen tidak dipenuhi dalam batas waktu'],
      ['Penolakan pengaduan berulang','Pengaduan yang sebelumnya telah diselesaikan dapat memenuhi kondisi penolakan sesuai ketentuan'],
      ['Batas kewenangan','Petugas wajib mengetahui kapan pengaduan dapat diselesaikan sendiri dan kapan harus dieskalasi'],
      ['Rekapitulasi pengaduan','Data pengaduan dihimpun untuk pelaporan, evaluasi, dan perbaikan kualitas proses layanan']
    ],
    10:[
      ['Pembukaan rekening dana','Proses membuat rekening simpanan setelah persyaratan nasabah dipenuhi'],
      ['Pembukaan rekening kredit','Proses membuka rekening fasilitas kredit setelah keputusan dan persyaratan kredit terpenuhi'],
      ['CIF','Customer Information File yang menjadi identitas nasabah di sistem bank'],
      ['KYC','Prinsip mengenal nasabah yang diterapkan dalam proses pembukaan hubungan usaha'],
      ['Verifikasi identitas','Bank memastikan dokumen identitas benar dan sesuai dengan pihak yang membuka rekening'],
      ['Kelengkapan dokumen','Dokumen pembukaan atau penutupan harus diperiksa sebelum proses dilanjutkan'],
      ['Akurasi input sistem','Data yang dimasukkan ke sistem harus sama dengan dokumen dan informasi nasabah'],
      ['Otorisasi pejabat','Tahap tertentu membutuhkan persetujuan pihak yang memiliki kewenangan'],
      ['Syarat produk rekening','Ketentuan produk perlu dijelaskan dan dipenuhi sebelum rekening dibuka'],
      ['Transparansi','Nasabah perlu memperoleh informasi yang jelas mengenai hak, kewajiban, biaya, dan ketentuan rekening'],
      ['Akuntabilitas','Setiap tahapan pembukaan dan penutupan harus memiliki tanggung jawab yang jelas dan dapat ditelusuri'],
      ['Pelindungan konsumen','Proses rekening harus menjaga hak nasabah dan mencegah informasi atau tindakan yang merugikan'],
      ['Administrasi dokumen','Dokumen pembukaan dan penutupan disimpan secara rapi sesuai prosedur'],
      ['Penutupan atas permintaan nasabah','Salah satu alasan rekening dapat ditutup adalah permintaan pemilik rekening'],
      ['Penutupan karena pertimbangan bank','Bank dapat menutup rekening ketika terdapat dasar yang sesuai ketentuan internal dan regulasi'],
      ['DHN','Daftar Hitam Nasional yang relevan pada kondisi tertentu terkait penarikan cek atau bilyet giro kosong'],
      ['Cek kosong','Penarikan cek tanpa dana yang cukup dapat menimbulkan konsekuensi sesuai ketentuan rekening giro'],
      ['Bilyet giro kosong','Penarikan bilyet giro yang tidak dapat dipenuhi dapat menjadi dasar tindakan sesuai ketentuan'],
      ['Permohonan penutupan kredit','Tahap awal ketika nasabah meminta rekening kredit ditutup'],
      ['Verifikasi sisa pokok','Sebelum rekening kredit ditutup, bank memeriksa sisa pokok yang masih harus dibayar'],
      ['Verifikasi bunga','Bunga yang masih terutang harus diperhitungkan sebelum pelunasan akhir'],
      ['Verifikasi denda','Denda atau kewajiban lain diperiksa agar tidak ada kewajiban tertinggal saat penutupan'],
      ['Pelunasan akhir','Nasabah menyelesaikan seluruh kewajiban sebelum rekening kredit ditutup'],
      ['Surat lunas','Bukti yang diterbitkan bank setelah kewajiban kredit dinyatakan selesai'],
      ['Pengembalian agunan','Dokumen atau barang jaminan dikembalikan setelah kewajiban dan prosedur penutupan terpenuhi'],
      ['Pengembalian dokumen pendukung','Dokumen yang menjadi hak nasabah dikembalikan sesuai ketentuan setelah kredit lunas'],
      ['Penutupan sistem','Tahap administratif terakhir untuk mengakhiri rekening kredit pada sistem bank'],
      ['Kejelasan alasan penutupan','Dasar penutupan harus dapat dijelaskan dan didokumentasikan'],
      ['Verifikasi saat penutupan','Identitas dan kewenangan pihak yang meminta penutupan harus dipastikan kembali'],
      ['Jejak audit','Dokumen dan otorisasi proses harus memungkinkan pemeriksa menelusuri siapa melakukan apa dan kapan'],
      ['Bukti kepemilikan rekening','Setelah pembukaan, bukti atau sarana kepemilikan diserahkan sesuai jenis produk dan prosedur'],
      ['Kepatuhan prosedur','Kecepatan layanan tidak boleh menggantikan verifikasi, otorisasi, dan dokumentasi yang diwajibkan']
    ],
    11:[
      ['Transaksi tunai','Transaksi yang melibatkan penerimaan atau penyerahan uang fisik'],
      ['Transaksi non tunai','Transaksi yang diselesaikan melalui rekening, warkat, atau instrumen pembayaran tanpa uang fisik'],
      ['Kesiapan aplikasi','Sistem transaksi harus siap sebelum layanan operasional dimulai'],
      ['Saldo fisik uang tunai','Ketersediaan kas harus dipastikan agar transaksi tunai dapat dilayani dengan aman'],
      ['Kesiapan warkat','Warkat yang diperlukan untuk transaksi harus tersedia dan dapat diproses sesuai ketentuan'],
      ['Verifikasi warkat','Petugas meneliti keabsahan dan kelengkapan instrumen transaksi sebelum pemrosesan'],
      ['Kelengkapan pengisian','Formulir atau voucher transaksi harus diisi lengkap agar instruksi nasabah jelas'],
      ['Akurasi pencatatan','Nominal, rekening, tanggal, dan informasi transaksi harus dicatat dengan benar'],
      ['Keamanan penerimaan uang','Uang tunai yang diterima harus dihitung, diperiksa, dan diamankan sesuai prosedur'],
      ['Keamanan penyerahan uang','Uang yang dibayarkan kepada nasabah harus dihitung dan diserahkan dengan kontrol yang benar'],
      ['Ciri keaslian uang','Petugas tunai perlu mampu meneliti tanda-tanda keaslian uang'],
      ['Voucher setoran','Dokumen instruksi yang digunakan untuk mencatat transaksi penyetoran sesuai prosedur'],
      ['Voucher penarikan','Dokumen instruksi penarikan yang harus diverifikasi sebelum dana dibayarkan'],
      ['Voucher transfer','Instruksi pemindahan dana yang memerlukan data penerima dan nominal yang akurat'],
      ['Penyerahan warkat ke back office','Warkat non tunai diteruskan secara tertib kepada unit pemroses berikutnya'],
      ['Rekonsiliasi akhir hari','Catatan transaksi dibandingkan dengan saldo fisik dan warkat untuk memastikan kesesuaian'],
      ['Selisih kas','Perbedaan antara catatan sistem dan uang fisik yang harus segera ditelusuri'],
      ['Serah terima saldo fisik','Kas diserahkan kepada penyelia sesuai prosedur dan bukti serah terima'],
      ['Otorisasi transaksi','Transaksi tertentu memerlukan persetujuan sesuai limit kewenangan'],
      ['Limit kewenangan','Batas nominal atau jenis transaksi menentukan siapa yang berhak mengotorisasi'],
      ['Pemeriksaan rekening sumber','Saldo dan status rekening diperiksa sebelum transaksi debet diproses'],
      ['Pemeriksaan rekening tujuan','Nomor dan identitas rekening penerima harus sesuai instruksi nasabah'],
      ['Pencocokan nominal','Angka pada voucher, uang, warkat, dan sistem harus konsisten'],
      ['Pencocokan tanda tangan','Tanda tangan pada instrumen tertentu diverifikasi sesuai specimen atau ketentuan'],
      ['KYC pada transaksi','Petugas menerapkan prinsip mengenal nasabah ketika karakter atau nilai transaksi memerlukannya'],
      ['Underlying document','Dokumen pendukung diperlukan pada transaksi tertentu untuk menjelaskan dasar dan tujuan transaksi'],
      ['Eskalasi transaksi tidak wajar','Transaksi yang tidak sesuai profil atau menimbulkan red flag diteruskan kepada fungsi terkait'],
      ['Dual control','Kontrol yang melibatkan lebih dari satu pihak untuk mengurangi risiko kesalahan atau penyalahgunaan'],
      ['Bukti transaksi','Nasabah memperoleh bukti bahwa transaksi telah diproses sesuai instruksi'],
      ['Kerahasiaan transaksi','Informasi transaksi hanya diberikan kepada pihak yang berhak sesuai ketentuan'],
      ['Cut-off operasional','Waktu batas pemrosesan dapat menentukan kapan transaksi tertentu diselesaikan'],
      ['Audit trail transaksi','Sistem dan dokumen harus menyimpan jejak pemrosesan agar transaksi dapat ditelusuri']
    ]
  },{
    7:'1 Layanan Info Produk dan Jasa Perbankan.pdf',
    8:'2 Edukasi Nasabah.pdf',
    9:'3 Menangani Pengaduan Nasabah.pdf',
    10:'4 Memproses Pembukaan dan Penutupan Rekening.pdf',
    11:'5 Memproses Transaksi Tunai dan Non Tunai.pdf'
  });
})();